package main

var (
	coverNames = []string{
		"NETFramework",
		"Go",
		"Android",
		"AngularJS",
		"Angular2",
		"Bash",
		"C",
		"CSS",
		"CSharp",
		"Cpp",
		"Excel",
		"Git",
		"GNULinux",
		"HTML",
		"HTMLCanvas",
		"Haskell",
		"iOS",
		"Java",
		"JavaScript",
		"jQuery",
		"MATLAB",
		"MongoDB",
		"MySQL",
		"Node.js",
		"ObjectiveC",
		"OracleDatabase",
		"PHP",
		"Perl",
		"PostgreSQL",
		"PowerShell",
		"Python",
		"R",
		"Ruby",
		"RubyOnRails",
		"SQL",
		"SQLServer",
		"Swift",
		"TypeScript",
		"VBA",
		"VisualBasicNET",
	}
	langToCover = map[string]string{
		"android": "Android",
		"go":      "Go",

		"Angular2":       "angular2",
		"AngularJS":      "angularjs",
		"Bash":           "bash",
		"C":              "c",
		"CSS":            "css",
		"CSharp":         "csharp",
		"Cpp":            "cpp",
		"Excel":          "excel",
		"GNULinux":       "gnulinux",
		"Git":            "git",
		"HTML":           "html",
		"HTMLCanvas":     "htmlcanvas",
		"Haskell":        "haskell",
		"Java":           "java",
		"JavaScript":     "javascript",
		"MATLAB":         "matlab",
		"MongoDB":        "mongodb",
		"MySQL":          "mysql",
		"NETFramework":   "netframework",
		"Node.js":        "nodejs",
		"ObjectiveC":     "objectivec",
		"OracleDatabase": "oracledatabase",
		"PHP":            "php",
		"Perl":           "perl",
		"PostgreSQL":     "postgresql",
		"PowerShell":     "powershell",
		"Python":         "python",
		"R":              "r",
		"Ruby":           "ruby",
		"RubyOnRails":    "rubyoneails",
		"SQL":            "sql",
		"SQLServer":      "sqlserver",
		"Swift":          "swift",
		"TypeScript":     "typescript",
		"VBA":            "vga",
		"VisualBasicNET": "visualbasicnet",
		"iOS":            "ios",
		"jQuery":         "jquery",
	}
)
