package main

var (
	coverNames = []string{
		"NETFramework",
		"Go",
		"Algorithms",
		"Android",
		"AngularJS",
		"Angular2",
		"Bash",
		"C",
		"CSS",
		"CSharp",
		"Cpp",
		"Excel",
		"Git",
		"GNULinux",
		"HTML",
		"HTMLCanvas",
		"Haskell",
		"iOS",
		"Java",
		"JavaScript",
		"jQuery",
		"MATLAB",
		"MongoDB",
		"MySQL",
		"Node.js",
		"ObjectiveC",
		"OracleDatabase",
		"PHP",
		"Perl",
		"PostgreSQL",
		"PowerShell",
		"Python",
		"R",
		"Ruby",
		"RubyOnRails",
		"SQL",
		"SQLServer",
		"Swift",
		"TypeScript",
		"VBA",
		"VisualBasicNET",
	}

	langToCover = map[string]string{
		"android":    "Android",
		"go":         "Go",
		"algorithms": "Algorithms",

		"Angular2":       "Angular2",
		"AngularJS":      "AngularJS",
		"Bash":           "Bash",
		"C":              "C",
		"CSS":            "CSSs",
		"CSharp":         "CSharp",
		"Cpp":            "Cpp",
		"Excel":          "Excel",
		"GNULinux":       "GNULinux",
		"Git":            "Git",
		"HTML":           "HTML",
		"HTMLCanvas":     "HTMLCanvas",
		"Haskell":        "Haskell",
		"Java":           "Java",
		"JavaScript":     "JavaScript",
		"MATLAB":         "MATLAB",
		"MongoDB":        "MongoDB",
		"MySQL":          "MySQL",
		"NETFramework":   "NETFramework",
		"Node.js":        "Node.js",
		"ObjectiveC":     "ObjectivecC",
		"OracleDatabase": "OracleDatabase",
		"PHP":            "PHP",
		"Perl":           "Perl",
		"PostgreSQL":     "PostgreSQL",
		"PowerShell":     "PowerShell",
		"Python":         "Python",
		"R":              "R",
		"Ruby":           "Ruby",
		"RubyOnRails":    "RubyOnRails",
		"SQL":            "SQL",
		"SQLServer":      "SQLServer",
		"Swift":          "Swift",
		"TypeScript":     "TypeScript",
		"VBA":            "VBA",
		"VisualBasicNET": "VisualBasicNET",
		"iOS":            "iOs",
		"jQuery":         "jQuery",
	}
)
