package main

import (
	"bytes"
	"fmt"
	"io"
	"path"
	"strings"

	"github.com/alecthomas/chroma"
	"github.com/alecthomas/chroma/formatters/html"
	"github.com/alecthomas/chroma/lexers"
	"github.com/alecthomas/chroma/styles"
	"github.com/gomarkdown/markdown"
	"github.com/gomarkdown/markdown/ast"
	mdhtml "github.com/gomarkdown/markdown/html"
	"github.com/gomarkdown/markdown/parser"
	"github.com/kjk/u"
	"github.com/microcosm-cc/bluemonday"
)

var (
	htmlFormatter  *html.Formatter
	highlightStyle *chroma.Style
)

// HeadingInfo describes # heading in markdown text
type HeadingInfo struct {
	Text string
	ID   string
}

func init() {
	htmlFormatter = html.New(html.WithClasses(), html.TabWidth(2))
	u.PanicIf(htmlFormatter == nil, "couldn't create html formatter")
	styleName := "monokailight"
	highlightStyle = styles.Get(styleName)
	u.PanicIf(highlightStyle == nil, "didn't find style '%s'", styleName)
}

// based on https://github.com/alecthomas/chroma/blob/master/quick/quick.go
func htmlHighlight(w io.Writer, source, lang, defaultLang string) error {
	if lang == "" {
		lang = defaultLang
	}
	l := lexers.Get(lang)
	if l == nil {
		l = lexers.Analyse(source)
	}
	if l == nil {
		l = lexers.Fallback
	}
	l = chroma.Coalesce(l)

	it, err := l.Tokenise(nil, source)
	if err != nil {
		return err
	}
	return htmlFormatter.Format(w, highlightStyle, it)
}

func isArticleOrChapterLink(s string) bool {
	return strings.HasPrefix(s, "a-")
}

var didPrint = false

func printKnownURLS(a []string) {
	if didPrint {
		return
	}
	didPrint = true
	fmt.Printf("%d known urls\n", len(a))
	for _, s := range a {
		fmt.Printf("%s\n", s)
	}
}

// turn partial url like "a-20381" into a full url like "a-20381-installing"
func fixupURL(uri string, knownURLS []string) string {
	if !isArticleOrChapterLink(uri) {
		return uri
	}
	for _, known := range knownURLS {
		if uri == known {
			return uri
		}
		if strings.HasPrefix(known, uri) {
			//fmt.Printf("fixupURL: %s => %s\n", uri, known)
			return known
		}
	}
	fmt.Printf("fixupURL: didn't fix up: %s\n", uri)
	//printKnownURLS(knownURLS)
	return uri
}

// CodeBlockInfo represents parsed lang line in
// markdown code block:
// ${lang}|githbu|${uri}|playground|${uri}
// every part is optional
type CodeBlockInfo struct {
	Lang          string
	GitHubURI     string
	PlaygroundURI string
}

func parseCodeBlockInfo(s string) *CodeBlockInfo {
	var res CodeBlockInfo
	s = strings.TrimSpace(s)
	if len(s) == 0 {
		return &res
	}
	parts := strings.Split(s, "|")
	res.Lang = parts[0]
	parts = parts[1:]
	// now we have pairs of values: (github, uri), (playground, uri)
	u.PanicIf(len(parts)%2 != 0)
	if len(parts) == 0 {
		return &res
	}
	n := len(parts) / 2
	for i := 0; i < n; i++ {
		key := parts[i*2]
		val := parts[i*2+1]
		switch key {
		case "github":
			res.GitHubURI = val
		case "playground":
			res.PlaygroundURI = val
		default:
			err := fmt.Errorf("invalid lang line '%s'", s)
			u.PanicIfErr(err)
		}
	}
	return &res
}

// gross hack. we need change html generated by chroma
func fixupHTMLCodeBlock(htmlCode string, info *CodeBlockInfo) string {
	if info.GitHubURI == "" && info.PlaygroundURI == "" {
		html := fmt.Sprintf(`
<div class="code-box">
	<div>
		%s
	</div>
</div>`, htmlCode)
		return html
	}

	playgroundPart := ""
	if info.PlaygroundURI != "" {
		playgroundPart = fmt.Sprintf(`
<div class="code-box-playground">
	<a href="%s" target="_blank">try online</a>
</div>
`, info.PlaygroundURI)
	}

	gitHubPart := ""
	if info.GitHubURI != "" {
		// gitHubLoc is sth. like github.com/essentialbooks/books/books/go/main.go
		fileName := path.Base(info.GitHubURI)
		gitHubPart = fmt.Sprintf(`
<div class="code-box-github">
	<a href="%s" target="_blank">%s</a>
</div>`, info.GitHubURI, fileName)
	}

	html := fmt.Sprintf(`
<div class="code-box">
	<div>
	%s
	</div>
	<div class="code-box-nav">
		%s
		%s
	</div>
</div>`, htmlCode, playgroundPart, gitHubPart)
	return html
}

// knownUrls is a list of chapter/article urls in the form "a-20381-installing"
func makeRenderHookCodeBlock(defaultLang string, book *Book) mdhtml.RenderNodeFunc {
	return func(w io.Writer, node ast.Node, entering bool) (ast.WalkStatus, bool) {

		if codeBlock, ok := node.(*ast.CodeBlock); ok {
			info := parseCodeBlockInfo(string(codeBlock.Info))
			//fmt.Printf("lang: %s, gitHubLoc: %s\n", lang, gitHubLoc)
			if false {
				fmt.Printf("lang: '%s', code: %s\n", info.Lang, string(codeBlock.Literal[:16]))
				io.WriteString(w, "\n"+`<pre class="chroma"><code>`)
				mdhtml.EscapeHTML(w, codeBlock.Literal)
				io.WriteString(w, "</code></pre>\n")
			} else {
				//fmt.Printf("\n----\n%s\n----\n", string(codeBlock.Literal))
				var tmp bytes.Buffer
				htmlHighlight(&tmp, string(codeBlock.Literal), info.Lang, defaultLang)
				d := tmp.Bytes()
				s := fixupHTMLCodeBlock(string(d), info)
				io.WriteString(w, s)
			}
			return ast.GoToNext, true
		} else if link, ok := node.(*ast.Link); ok {
			// fix up the url if it's a prefix of known url and let original code to render it
			dest := string(link.Destination)
			link.Destination = []byte(fixupURL(dest, book.knownUrls))
			return ast.GoToNext, false
		} else {
			return ast.GoToNext, false
		}
	}
}

func markdownToUnsafeHTML(md []byte, defaultLang string, book *Book) []byte {
	extensions := parser.NoIntraEmphasis |
		parser.Tables |
		parser.FencedCode |
		parser.Autolink |
		parser.Strikethrough |
		parser.SpaceHeadings |
		parser.NoEmptyLineBeforeBlock |
		parser.AutoHeadingIDs
	parser := parser.NewWithExtensions(extensions)

	htmlFlags := mdhtml.Smartypants |
		mdhtml.SmartypantsFractions |
		mdhtml.SmartypantsDashes |
		mdhtml.SmartypantsLatexDashes
	htmlOpts := mdhtml.RendererOptions{
		Flags:          htmlFlags,
		RenderNodeHook: makeRenderHookCodeBlock(defaultLang, book),
	}
	renderer := mdhtml.NewRenderer(htmlOpts)
	return markdown.ToHTML(md, parser, renderer)
}

func markdownToHTML(d []byte, defaultLang string, book *Book) string {
	unsafe := markdownToUnsafeHTML(d, defaultLang, book)
	policy := bluemonday.UGCPolicy()
	policy.AllowStyling()
	policy.RequireNoFollowOnFullyQualifiedLinks(false)
	policy.RequireNoFollowOnLinks(false)
	policy.AllowAttrs("target").OnElements("a")
	res := policy.SanitizeBytes(unsafe)
	return string(res)
}

func getTextRecur(node ast.Node) string {
	if text, ok := node.(*ast.Text); ok {
		return string(text.Literal)
	}
	if code, ok := node.(*ast.Code); ok {
		return string(code.Literal)
	}
	s := ""
	for _, child := range node.GetChildren() {
		s += getTextRecur(child)
	}
	return s
}

func parseHeadingsFromMarkdown(d []byte) []HeadingInfo {
	var res []HeadingInfo
	extensions := parser.NoIntraEmphasis |
		parser.Tables |
		parser.FencedCode |
		parser.Autolink |
		parser.Strikethrough |
		parser.SpaceHeadings |
		parser.NoEmptyLineBeforeBlock |
		parser.AutoHeadingIDs
	parser := parser.NewWithExtensions(extensions)
	astRoot := markdown.Parse(d, parser)
	ast.WalkFunc(astRoot, func(node ast.Node, entering bool) ast.WalkStatus {
		if entering {
			if heading, ok := node.(*ast.Heading); ok {
				s := getTextRecur(heading)
				s = strings.TrimSpace(s)
				if len(s) > 0 {
					h := HeadingInfo{
						Text: s,
						ID:   heading.HeadingID,
					}
					res = append(res, h)
				}
			}
		}
		return ast.GoToNext
	})
	return res
}
